package edge.core.modules.auth;

// Generated Feb 1, 2012 8:07:27 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import edge.core.modules.common.EdgeEntity;

/**
 * Authorities generated by hbm2java
 */
@Entity
@Table(name = "authorities", uniqueConstraints = @UniqueConstraint(columnNames = {
		"USERNAME", "AUTHORITY" }))
public class AuthorityEntity extends EdgeEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer authoritiesId;
	private String username;
	private String authority;

	public AuthorityEntity() {
	}

	public AuthorityEntity(String username, String authority) {
		this.username = username;
		this.authority = authority;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AUTHORITIES_ID", unique = true, nullable = false)
	public Integer getAuthoritiesId() {
		return this.authoritiesId;
	}

	public void setAuthoritiesId(Integer authoritiesId) {
		this.authoritiesId = authoritiesId;
	}

	@Column(name = "USERNAME", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "AUTHORITY", nullable = false, length = 50)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
